export const SOCKET_EVENTS = {
  INDIVIDUAL: {
    REQUEST: 'individual:request',
    MESSAGE_SEND: 'individual:message',
    MESSAGE_RECEIVED: 'chat:message:received',
    READ_CHATS: 'individual:read:chats',
    LEAVE_CHATS: 'individual:leave:chats',
    DELETE_CHAT: 'individual:chat:delete',
    CHAT_DELETED: 'chat:deleted',
    SHARE_CONTENT: 'individual:message:share',
    BLOCK_USER: 'individual:block:user',
    CHAT_BLOCKED: 'chat:blocked',
    COMMENT: 'individual:comment',
  },
  LIVE: {
    JOIN: 'live:join',
    MESSAGE_SEND: 'live:message',
    LEAVE: 'live:leave',
    END: 'live:end',
    USER_JOINED: 'live:user:joined',
    MESSAGE_RECEIVED: 'live:message:received',
    USER_LEFT: 'live:user:left',
    ENDED: 'live:ended',
  },
  GROUP: {
    JOIN: 'group:join',
    SEND_MESSAGE: 'group:message:send',
    LEAVE_ROOM: 'group:leave:room',
    LEAVE_GROUP: 'group:leave:group',
    DELETE_GROUP: 'group:delete',
    ADD_MEMBERS: 'group:members:add',
    REMOVE_MEMBER: 'group:remove:member',
    SHARE_CONTENT: 'group:message:share',
    MESSAGE_RECEIVED: 'group:message:received',
    GROUP_DELETED: 'group:deleted',
    ADDED_TO_GROUP: 'group:member:added',
    ADMIN_REMOVED_YOU: 'group:admin:removed:you',
  },
  COMMON: {
    USER_STATUS: 'user:status',
    USER: 'user',
  },
};