export const SOCKET_EVENTS = {
  INDIVIDUAL: {
    REQUEST: 'individual:request',
    MESSAGE_SEND: 'individual:message_send',
    MESSAGE_RECEIVED: 'individual:message_received',
    READ_CHATS: 'individual:read_chats',
    LEAVE_CHATS: 'individual:leave_chats',
    DELETE_CHAT: 'individual:delete_chat',
    CHAT_DELETED: 'individual:chat_deleted',
    SHARE_CONTENT: 'individual:share_content',
    BLOCK_USER: 'individual:block_user',
    CHAT_BLOCKED: 'individual:chat_blocked',
    COMMENT: 'individual:comment',
  },
  LIVE: {
    JOIN: 'live:join',
    MESSAGE_SEND: 'live:message_send',
    LEAVE: 'live:leave',
    END: 'live:end',
    USER_JOINED: 'live:user_joined',
    MESSAGE_RECEIVED: 'live:message_received',
    USER_LEFT: 'live:user_left',
    ENDED: 'live:ended',
  },
  GROUP: {
    JOIN: 'group:join',
    SEND_MESSAGE: 'group:send_message',
    LEAVE_ROOM: 'group:leave_room',
    LEAVE_GROUP: 'group:leave_group',
    DELETE_GROUP: 'group:delete_group',
    ADD_MEMBERS: 'group:add_members',
    REMOVE_MEMBER: 'group:remove_member',
    SHARE_CONTENT: 'group:share_content',
    MESSAGE_RECEIVED: 'group:message_received',
    GROUP_DELETED: 'group:group_deleted',
    ADDED_TO_GROUP: 'group:added_to_group',
    ADMIN_REMOVED_YOU: 'group:admin_removed_you',
  },
  COMMON: {
    USER_STATUS: 'user_status',
    USER: 'user',
  },
};